name: hyperblue
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41 # latest is also supported if you want new updates ASAP

modules:

  - type: files
    files:
      - source: usr   # copies `files/usr/*` to `/usr/` inside the image
        destination: /usr

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      # remove:
      # - org.gnome.eog
      install:
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - com.github.tchx84.Flatseal
        - com.protonvpn.www
        - me.proton.Pass
        - me.proton.Mail
        - md.obsidian.Obsidian
        - re.sonny.Junction

  - type: bling
    install:
      - rpmfusion
      - dconf-update-service

  - type: rpm-ostree
  # repos:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    remove:
      - gnome-shell
      - gnome-shell-extensions
      - gnome-session
      - gnome-calendar
      - gnome-screenshot
      - gnome-maps
      - gnome-music
      - gnome-photos
      - gnome-software
      - gnome-weather
      - gnome-clocks
      - gnome-logs
      - gnome-books
      - gnome-documents
      - gnome-control-center
      - gnome-tweaks
      - gnome-disk-utility
      - gnome-sound-recorder
      - gnome-remote-desktop
      - gnome-backgrounds
      - yaru-theme
      - mutter
      - gnome-settings-daemon
      - orca
      - at-spi2-core
      - at-spi2-atk
      - gnome-builder
      - gnome-terminal-server
      - network-manager-gnome
      - gnome-bluetooth
      - gnome-chess
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      - gnome-help
      - gnome-user-docs
      - gnome-characters
      - gnome-font-viewer
      - gnome-sound-recorder
      - gnome-video-effects
      - gnome-session-bin
      - gnome-session-common
      - gnome-shell-common
      - gnome-icon-theme
      - gnome-icon-theme-symbolic
    install:
      - waydroid
      - zerotier-one

  # enable linuxbrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry


### Extras ###

  # install zerotier
  # - type: script
  #  snippets:
  #    - 'curl -s ''https://raw.githubusercontent.com/zerotier/ZeroTierOne/main/doc/contact%40zerotier.com.gpg'' | gpg --import && if z=$(curl -s ''https://install.zerotier.com/'' | gpg); then echo "$z" | bash || true; fi'

  # install fnm
  - type: script
    snippets:
      - 'curl -fsSL https://fnm.vercel.app/install | bash'

  # install deno
  - type: script
    snippets:
      - 'curl -fsSL https://bun.sh/install | bash'

  # install bun
  - type: script
    snippets:
      - 'curl -fsSL https://bun.sh | bash'

  # install luvit
  - type: script
    snippets:
      - 'cd /usr/bin && curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh'

  # scripts.
  - type: script
    # snippets:
    #   - "curl https://example.com/examplebinary > /usr/bin/examplebinary" # example: download binary
    #   - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld" # example: ld alternatives symlink workaround
    scripts: # scripts in config/scripts/
      - install_lite-xl.sh
      - install_extras.sh

  # sign images.
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
