name: hyperblue
description: Custom image for bluefin-dx with waydroid, hyprland and essential development tools.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41

modules:

### Base ###
  - type: files
    files:
      - source: usr
        destination: /usr

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      remove:
        - org.gnome.eog
      install:
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - com.github.tchx84.Flatseal
        - com.protonvpn.www
        - me.proton.Pass
        - me.proton.Mail
        - md.obsidian.Obsidian
        - re.sonny.Junction

  - type: bling
    install:
      - rpmfusion
      - dconf-update-service

  - type: rpm-ostree
    remove:
      - gnome-shell
      - gnome-session
      - gnome-settings-daemon
      - gnome-control-center
      - gnome-tweaks
      - gnome-terminal
      - gnome-software
      - mutter

    install:
      - waydroid
      - zerotier-one

  # enable linuxbrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry


### Extras ###

  # run scripts
  - type: script
    scripts: # scripts in config/scripts/
      - install_devtools.sh
      - install_lite-xl.sh
      - install_extras.sh

  # sign images.
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
