name: hyperblue
description: Custom image for bluefin-dx with waydroid, hyprland and essential development tools.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41

modules:

### Base ###
  - type: files
    files:
      # copy base recipe files
      - source: usr
        destination: /usr
      # copy user files
      - source: /etc/skel
        destination: /etc/skel/

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      remove:
        - org.gnome.eog
      install:
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - app.devsuite.Ptyxis
        - com.github.tchx84.Flatseal
        - io.github.flattool.Warehouse
        - io.github.dvlv.boxbuddyrs
        - com.usebottles.bottles
        - com.interversehq.qView
        - com.protonvpn.www
        - me.proton.Pass
        - me.proton.Mail
        - md.obsidian.Obsidian
        - re.sonny.Junction
        - io.mpv.Mpv
        - com.stremio.Stremio
        - org.gimp.GIMP
        - org.onlyoffice.desktopeditors
        - org.nickvision.tubeconverter
        - com.github.finefindus.eyedropper
        - org.upscayl.Upscayl
  
  - type: bling
    install:
      - rpmfusion
      - dconf-update-service

  - type: rpm-ostree
    install:
      - htop
      - waydroid
      - zerotier-one
      - podman
      - podman-compose

  - type: systemd
    system:
      enabled:
        - sshd.service
        - zerotier-one.service
    user:
      enabled:
        - podman.service

  # enable linuxbrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - from-file: hyprland.yml

### Extras ###

  # run scripts
  - type: script
    scripts: # scripts in config/scripts/
      - install_devtools.sh
      - install_lite-xl.sh
      - install_extras.sh

  # sign images.
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
