name: hyperblue
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - type: rpm-ostree
  # repos:
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo

    install:
      - waydroid
    # - micro
    # - starship
  # remove:
  # example: removing firefox (in favor of the flatpak)
  # "firefox" is the main package, "firefox-langpacks" is a dependency
  # - firefox
  # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: files
    files:
      - source: usr   # copies `files/usr/*` to `/usr/` inside the image
        destination: /usr

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
        - com.github.tchx84.Flatseal
        - com.protonvpn.www
        - me.proton.Pass
        - me.proton.Mail
        - re.sonny.Junction
        - md.obsidian.Obsidian

      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      # remove:
      # - org.gnome.eog

  # fix permissions on /usr/local/bin
  - type: script
    snippets:
      - 'chmod -R 755 /usr/local/bin'


  - type: bling
    install:
      - rpmfusion
      - dconf-update-service

  # enable linuxbrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry


  ### Extras ###

  # install zerotier
  - type: script
    snippets:
      - 'curl -s ''https://raw.githubusercontent.com/zerotier/ZeroTierOne/main/doc/contact%40zerotier.com.gpg'' | gpg --import && if z=$(curl -s ''https://install.zerotier.com/'' | gpg); then echo "$z" | bash || true; fi'

  # install fnm
  - type: script
    snippets:
      - 'curl -fsSL https://fnm.vercel.app/install | bash'

  # install deno
  - type: script
    snippets:
      - 'curl -fsSL https://bun.sh/install | bash'

  # install bun
  - type: script
    snippets:
      - 'curl -fsSL https://bun.sh | bash'

  # install luvit
  - type: script
    snippets:
      - 'curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh'

  # scripts.
  - type: script
    # snippets:
    #   - "curl https://example.com/examplebinary > /usr/bin/examplebinary" # example: download binary
    #   - "ln -sf /usr/bin/ld.bfd /etc/alternatives/ld && ln -sf /etc/alternatives/ld /usr/bin/ld" # example: ld alternatives symlink workaround
    scripts: # scripts in config/scripts/
      - install_lite-xl.sh
      - install_extras.sh

  # sign images.
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
