# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyperblue
description: Custom image for bluefin-dx with waydroid, hyprland and essential development tools.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 42

modules:
  ### Base ###
  - type: files
    files:
      # copy base recipe files
      - source: usr
        destination: /usr
      # copy user files
      - source: /etc/skel
        destination: /etc/skel/

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      # - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service
      - rpmfusion

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
    install:
      # base
      - openssh-server # ssh server

      # terminal
      - alacritty # minimal terminal
      - micro # tui editor better than nano
      - zsh # shell

      # audio
      - pavucontrol
      - pipewire
      - playerctl
      - wireplumber

      # bluetooth
      - blueman

      # network
      - network-manager-applet
      - NetworkManager-l2tp-gnome
      - NetworkManager-libreswan-gnome
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-sstp-gnome
      - NetworkManager-vpnc-gnome

      # modern cli tools https://github.com/ibraheemdev/modern-unix
      - duf
      - eza
      - fd-find
      - httpie
      - procs
      - tldr

      # hyprland
      - hyprland
      - hyprpaper # wallpaper util
      - hyprpicker # color picker
      - hyprshot # screenshot util
      - xdg-desktop-portal-hyprland # desktop portal

      # qt
      - qt5-qtwayland
      - qt6-qtwayland

      # system utilities
      - system-config-printer
      - gnome-keyring-pam
      - fprintd-pam
      - lxqt-policykit
      - pinentry-gnome3
      - brightnessctl
      - plymouth-system-theme
      - wl-clipboard

      # display manager
      - sddm-wayland-generic

      # zerotier
      - zerotier-one

      # Desktop environment
      - waybar # status bar
      - swaylock # lock screen
      - dunst # notification daemon
      - rofi-wayland # application launcher
      - nautilus # file manager

      # dev tools
      - podman
      - podman-compose

      # other
      - htop # system monitor

    # remove:
    #   - firefox # default firefox removed in favor of flatpak
    #   - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: systemd
    system:
      enabled:
        - zerotier-one.service
    user:
      enabled:
        # - sshd.service
        - podman.service

  # enable linuxbrew
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      remove:
        - org.gnome.eog
      install:
        # System utilities
        - org.gnome.Firmware
        - app.devsuite.Ptyxis
        - io.missioncenter.MissionCenter # system information tool
        - com.github.tchx84.Flatseal # flatpak permissions manager
        - io.github.flattool.Warehouse # flatpak manager
        - com.ranfdev.DistroShelf # DistroBox manager
        - re.sonny.Junction # File Association Proxy
        - re.sonny.Eloquent # Grammar checker
        - com.github.wwmm.easyeffects # audio equalizer
        - org.pipewire.Helvum # pipewire graph visualizer
        - org.github.input_leap.input_leap # input sharing tool

        # Media
        - be.alexandervanhee.gradia # screenshot tool
        - org.js.nuclear.Nuclear # music player
        - org.kde.haruna # video player

        # Development tools
        - com.felipekinoshita.Wildcard # regex testing tool
        - io.github.zefr0x.hashes # hash calculator
        - net.werwolv.ImHex # hex editor
        - org.gnome.meld # diff tool
        - com.visualstudio.code
        - sh.loft.devpod

        # Internet
        - com.vivaldi.Vivaldi
        - de.schmidhuberj.tubefeeder # youtube client
        - io.github.giantpinkrobots.varia # download manager

        # Communication
        - io.github.equicord.equibop # discord client

  ### Extras ###

  # run scripts
  - type: script
    scripts: # scripts in config/scripts/
      - install_extras.sh

  # sign images.
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
